In [5]:
# 1- Create a numpy array of shape (3, 4) and assign random integers between 1 and 10 to every element.
import numpy as np
arr = np.random.randint(low=1, high=10, size=(3,4))
print(arr)

[[1 5 2 7]
 [1 3 5 6]
 [5 8 2 5]]


In [22]:
# 2- Find the maximum value in the array created in step 1.
import numpy as np
max_val = np.max(arr)
print(max_val)

9


In [26]:
# 3- Calculate the mean value of each row in the array.
import numpy as np
mean = np.mean(arr, axis = 1,dtype='int32')
print(mean)

[6 4 5]


In [36]:
# 4- Reshape the array from step 1 into a shape of (2, 6).
import numpy as np
reshape_arr = np.reshape(reshape_arr, (2,6))
print(reshape_arr)

[[7 8 7 2 4 1]
 [8 3 6 1 4 9]]


In [30]:
# 5- Multiply each element in the array by 2.
import numpy as np
print(arr*2)

[[14 16 14  4]
 [ 8  2 16  6]
 [12  2  8 18]]


In [8]:
# 6- Create a numpy array with values ranging from 0 to 9. Extract the odd numbers from the array.
import numpy as np
new_arr = np.arange(10)
print(new_arr)
odd_nums = new_arr[new_arr%2!=0]
print(odd_nums)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [7]:
# 7- Create a 3x3 identity matrix using numpy.
import numpy as np
idm = np.identity(3, dtype = 'int32')
print(idm)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [22]:
# 8- Create a 5x5 array with random values and normalize it (subtract the mean and divide by the standard deviation of the array).
import numpy as np
rarr = np.random.randint(50, size=(5,5))
print(rarr)
nrarr = (rarr - np.mean(rarr))/np.std(rarr)

[[11 39  4 20  7]
 [ 1 48 48 22 19]
 [37 43 16 47 38]
 [19 23  4 42 15]
 [20 14 28 31 42]]


In [31]:
# 9- Perform element-wise multiplication between two arrays of the same shape.
import numpy as np
arr1 = np.random.randint(10, size = (3,3))
print(arr1)
arr2 = np.random.randint(20, size = (3,3))
print(arr2)
print(arr1 * arr2)

[[9 7 2]
 [5 6 4]
 [4 0 7]]
[[ 0 18 18]
 [18  5 11]
 [11 14 15]]
[[  0 126  36]
 [ 90  30  44]
 [ 44   0 105]]


In [37]:
# 10 - Given an array of heights in centimeters, convert them to inches (1 inch = 2.54 cm).
arr_ht = np.array([4.5, 3.44, 5.67, 33.11, 2, 5])
print(arr_ht/2.54)

[ 1.77165354  1.35433071  2.23228346 13.03543307  0.78740157  1.96850394]


In [45]:
# 11 - Create a 1D array of numbers from 0 to 9. Replace all odd numbers with -1.
import numpy as np
arr = np.arange(10)
print(arr)
arr[arr%2!=0] = -1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [58]:
# 12 - Create a 2D array with random values and find the indices of the maximum and minimum values.
import numpy as np
arr = np.random.randint(low=5, high=25, size=(3,3))
print(arr)
maxidx = np.unravel_index(np.argmax(arr), arr.shape)
minidx = np.unravel_index(np.argmin(arr), arr.shape)
print(maxidx)
print(minidx)

[[24  8  8]
 [18  7 11]
 [ 7 23 19]]
(np.int64(0), np.int64(0))
(np.int64(1), np.int64(1))
